name: Wiki trigger

on:
  push:
    branches-ignore:
      - release
  pull_request:
    types: [closed, synchronize]
  gollum:

jobs:
  Dispatch_Workflow:
    if: (github.event_name == 'pull_request' || github.event_name == 'push')
    uses: gabor-kovac/workflow/.github/workflows/dispatch.yml@main

  Trigger_Wiki:
    if: (github.event_name == 'gollum')
    uses: gabor-kovac/workflow/.github/workflows/say_hi.yml@main
    secrets: inherit
