name: Wiki trigger

on:
  push:
    branches-ignore:
      - release
  pull_request:
    types: [closed, synchronize]
  gollum:

jobs:
  Trigger_Wiki:
    if: (github.event_name == 'gollum')
    uses: gabor-kovac/wiki-trig-test/.github/workflows/test-wf.yml@main

  Pull_Request:
    if: (github.event_name == 'pull_request')
    runs-on: ubuntu-latest
    steps:
      - run: echo "Triggered by pull request"

  Push:
    if: (github.event_name == 'push')
    runs-on: ubuntu-latest
    steps:
      - run: echo "Triggered by push"
